apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    component: {{ .Values.component_name }}
    template: {{ .Values.component_name }}
  name: {{ .Values.component_name }}
spec:
  output:
    pushSecret:
      name: jfrog
    to:
      kind: DockerImage
      name: {{ .Values.component_image }}
  resources:
    limits:
      cpu: {{ .Values.build_cpu_limit }}
      memory: {{ .Values.build_mem_limit }}
    requests:
      cpu: {{ .Values.build_cpu_request }}
      memory: {{ .Values.build_mem_request }}
  source:
    contextDir: {{ .Values.context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    secrets:
    - destinationDir: .m2
      secret:
        name: settings-mvn
    sourceSecret:
      name: gitsecret
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_SETTINGS_XML
        value: /opt/app-root/src/.m2/settings.xml
      from:
        kind: DockerImage
        name: {{ .Values.base_image }}:{{ .Values.base_image_tag }}
      pullSecret:
        name: jfrog
    type: Source
  triggers: []
