apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.component.name }}-mybuild
spec:
  source:
    git:
      uri: {{ .Values.source_repository.url }}
      ref: {{ .Values.source_repository.ref }}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.build.base_image }}:{{ .Values.build.base_image_tag }}
  output:
    to:
      kind: ImageStreamTag
      name: tss-tfcsduedateoverride:latest

  resources:
    limits:
      cpu: {{ .Values.build.resources.limits.cpu }}
      memory: {{ .Values.build.resources.limits.memory }}
    requests:
      cpu: {{ .Values.build.resources.requests.cpu }}
      memory: {{ .Values.build.resources.requests.memory }}

