apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Values.component.name }}-mydeployment
spec:
  replicas: {{ .Values.num_replicas }}
  selector:
    app: {{ .Values.component.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.component.name }}
    spec:
      containers:
        - name: {{ .Values.component.name }}-container
          image: {{ .Values.component.image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.deploy.resources.limits.cpu }}
              memory: {{ .Values.deploy.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deploy.resources.requests.cpu }}
              memory: {{ .Values.deploy.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.liveness_delay }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: {{ .Values.readiness_delay }}

