apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-service
spec:
  selector:
    app: {{ .Values.component.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

