apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    component: {{ .Values.component_name }}
    template: {{ .Values.component_name }}
  name: {{ .Values.component_name }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: fromweb
    port: 8081
    targetPort: 8081
  selector:
    name: {{ .Values.component_name }}
